site_name: cubao-pybind
site_url: https://cubao-pybind.readthedocs.io
site_description: misc c++ code in cubao
site_author: district10

repo_url: https://github.com/cubao/cubao-pybind
edit_uri: blob/master/docs/

theme: readthedocs
nav:
  - Home: index.md
  - Code: code.md
  - About:
      - Release Notes: about/release-notes.md
      - License: about/license.md
plugins:
  - include-markdown

copyright: Copyright &copy; 2023 <a href="https://cubao.readthedocs.io">cubao team</a>.
